[Emma_vertebrate_models]
git-tree-sha1 = "dd40b8f39029e9d2a79925f0a687ed4035b10159"

    [[Emma_vertebrate_models.download]]
    sha256 = "55788e8f9ddaaa9f798f81fca6b32acc9ee3fac56580ffe9e2c9f78aa1e4d022"
    url = "https://github.com/ian-small/emma-models/archive/refs/tags/v1.0.0.tar.gz"
